import type {
  Course,
  ContentItem,
  Announcement,
  Discussion,
  DiscussionPost,
  RosterMember,
  Notification,
  CalendarEvent,
  Assignment,
} from "./types"

export const courses: Course[] = [
  {
    id: "TEST-001",
    code: "202610-TEST-001",
    name: "Test Course 1",
    term: "202610",
    instructor: "Test Instructor",
    instructorRole: "Instructor",
    schedule: {
      days: "Monday, Wednesday",
      time: "10:00 AM - 11:15 AM",
      location: "Building A Room 101",
    },
    color: "#8B5CF6",
    isFavorite: true,
  },
]

export const contentItems: ContentItem[] = [
  {
    id: "content-1",
    courseId: "TEST-001",
    title: "Test Resource 1",
    type: "link",
  },
  {
    id: "content-2",
    courseId: "TEST-001",
    title: "Test Document 1",
    type: "document",
    hasAlert: true,
  },
  {
    id: "content-3",
    courseId: "TEST-001",
    title: "Test Folder 1",
    type: "folder",
    isExpanded: false,
  },
  {
    id: "content-4",
    courseId: "TEST-001",
    title: "Test Folder 2",
    type: "folder",
    isExpanded: false,
  },
  {
    id: "content-5",
    courseId: "TEST-001",
    title: "Test Folder 3",
    type: "folder",
    isExpanded: false,
  },
]

export const announcements: Announcement[] = [
  {
    id: "ann-1",
    courseId: "TEST-001",
    title: "Test Announcement 1",
    content: "This is test announcement content 1.",
    postedAt: "1 hour ago",
    isRead: false,
  },
  {
    id: "ann-2",
    courseId: "TEST-001",
    title: "Test Announcement 2",
    content: "This is test announcement content 2.",
    postedAt: "3/20",
    isRead: false,
  },
  {
    id: "ann-3",
    courseId: "TEST-001",
    title: "Test Announcement 3",
    content: "This is test announcement content 3.",
    postedAt: "3/15",
    isRead: true,
  },
  {
    id: "ann-4",
    courseId: "TEST-001",
    title: "Test Announcement 4",
    content: "This is test announcement content 4.",
    postedAt: "3/10",
    isRead: true,
  },
  {
    id: "ann-5",
    courseId: "TEST-001",
    title: "Test Announcement 5",
    content: "This is test announcement content 5.",
    postedAt: "3/1",
    isRead: true,
  },
]

export const discussions: Discussion[] = [
  {
    id: "disc-1",
    courseId: "TEST-001",
    title: "Test Discussion 1",
    description: "Post a short response for test discussion 1.",
    dueDate: "4/10/26, 11:59 PM (CST)",
    isFavorite: false,
    isCompleted: true,
    totalPosts: 12,
    totalReplies: 24,
    grade: { score: 20, total: 20 },
  },
  {
    id: "disc-2",
    courseId: "TEST-001",
    title: "Test Discussion 2",
    description: "Post a short response for test discussion 2.",
    dueDate: "4/17/26, 11:59 PM (CST)",
    isFavorite: false,
    isCompleted: false,
    totalPosts: 9,
    totalReplies: 15,
  },
  {
    id: "disc-3",
    courseId: "TEST-001",
    title: "Test Discussion 3",
    description: "Post a short response for test discussion 3.",
    dueDate: "4/24/26, 11:59 PM (CST)",
    isFavorite: false,
    isCompleted: false,
    totalPosts: 7,
    totalReplies: 10,
  },
]

export const discussionPosts: DiscussionPost[] = [
  {
    id: "post-1",
    discussionId: "disc-1",
    authorName: "Test User 1",
    content: "Test post content 1.",
    postedAt: "Apr 1, 2026 9:00 AM",
    isNew: true,
  },
  {
    id: "post-2",
    discussionId: "disc-1",
    authorName: "Test User 2",
    content: "Test post content 2.",
    postedAt: "Apr 1, 2026 10:20 AM",
    isNew: true,
  },
  {
    id: "post-3",
    discussionId: "disc-1",
    authorName: "Test User 3",
    content: "Test post content 3.",
    postedAt: "Mar 31, 2026 4:45 PM",
    isNew: false,
  },
  {
    id: "post-4",
    discussionId: "disc-1",
    authorName: "Test User 4",
    content: "Test post content 4.",
    postedAt: "Mar 30, 2026 11:15 AM",
    isNew: false,
  },
]

export const rosterMembers: RosterMember[] = [
  {
    id: "member-1",
    courseId: "TEST-001",
    name: "Test Instructor",
    role: "Instructor",
    email: "instructor1@test.edu",
  },
  {
    id: "member-2",
    courseId: "TEST-001",
    name: "Test Student 1",
    role: "Student",
    email: "student1@test.edu",
  },
  {
    id: "member-3",
    courseId: "TEST-001",
    name: "Test Student 2",
    role: "Student",
    email: "student2@test.edu",
  },
  {
    id: "member-4",
    courseId: "TEST-001",
    name: "Test Student 3",
    role: "Student",
    email: "student3@test.edu",
  },
  {
    id: "member-5",
    courseId: "TEST-001",
    name: "Test Student 4",
    role: "Student",
    email: "student4@test.edu",
  },
  {
    id: "member-6",
    courseId: "TEST-001",
    name: "Test Student 5",
    role: "Student",
    email: "student5@test.edu",
  },
  {
    id: "member-7",
    courseId: "TEST-001",
    name: "Test Student 6",
    role: "Student",
    email: "student6@test.edu",
  },
  {
    id: "member-8",
    courseId: "TEST-001",
    name: "Test Student 7",
    role: "Student",
    email: "student7@test.edu",
  },
  {
    id: "member-9",
    courseId: "TEST-001",
    name: "Test Student 8",
    role: "Student",
    email: "student8@test.edu",
  },
  {
    id: "member-10",
    courseId: "TEST-001",
    name: "Test Student 9",
    role: "Student",
    email: "student9@test.edu",
  },
  {
    id: "member-11",
    courseId: "TEST-001",
    name: "Test Student 10",
    role: "Student",
    email: "student10@test.edu",
  },
  {
    id: "member-12",
    courseId: "TEST-001",
    name: "Test Student 11",
    role: "Student",
    email: "student11@test.edu",
  },
]

export const notifications: Notification[] = [
  {
    id: "notif-1",
    title: "Test Notification 1",
    content: "A new test announcement is available.",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    type: "announcement",
    createdAt: "30 min ago",
    isRead: false,
    link: "/courses/TEST-001?tab=announcements",
  },
  {
    id: "notif-2",
    title: "Test Notification 2",
    content: "A test grade update was posted.",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    type: "grade",
    createdAt: "4/2/26, 10:00 AM",
    isRead: false,
    link: "/courses/TEST-001/discussions/disc-1",
  },
  {
    id: "notif-3",
    title: "Test Notification 3",
    content: "A test assignment is due soon.",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    type: "assignment",
    createdAt: "4/3/26, 12:00 PM",
    isRead: false,
    link: "/courses/TEST-001/assignments/assign-1",
  },
  {
    id: "notif-4",
    title: "Test Notification 4",
    content: "There is a new reply in a test discussion.",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    type: "discussion",
    createdAt: "4/4/26, 4:10 PM",
    isRead: false,
    link: "/courses/TEST-001/discussions/disc-1",
  },
  {
    id: "notif-5",
    title: "Test Notification 5",
    content: "A general test update was posted.",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    type: "announcement",
    createdAt: "4/1/26, 3:45 PM",
    isRead: true,
    link: "/courses/TEST-001?tab=announcements",
  },
  {
    id: "notif-6",
    title: "Test Notification 6",
    content: "Your test submission was received.",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    type: "assignment",
    createdAt: "3/30/26, 11:45 PM",
    isRead: true,
  },
  {
    id: "notif-7",
    title: "Test Notification 7",
    content: "You have a new test message.",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    type: "message",
    createdAt: "3/28/26, 2:30 PM",
    isRead: true,
  },
]

export const calendarEvents: CalendarEvent[] = [
  {
    id: "event-1",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    title: "Test Discussion 1",
    date: "2026-04-10",
    type: "discussion",
  },
  {
    id: "event-2",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    title: "Test Discussion 2",
    date: "2026-04-17",
    type: "discussion",
  },
  {
    id: "event-3",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    title: "Test Discussion 3",
    date: "2026-04-24",
    type: "discussion",
  },
  {
    id: "event-4",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    title: "Test Assignment 1 Due",
    date: "2026-04-15",
    type: "assignment",
  },
  {
    id: "event-5",
    courseId: "TEST-001",
    courseName: "Test Course 1",
    title: "Test Exam 1",
    date: "2026-04-20",
    type: "exam",
  },
]

// Participation data for discussions
export const discussionParticipants = [
  { name: "Test User (Me)", posts: 1, replies: 2, isCurrentUser: true },
  { name: "Test User 1", posts: 1, replies: 1 },
  { name: "Test User 2", posts: 2, replies: 2 },
  { name: "Test User 3", posts: 1, replies: 0 },
]

export const assignments: Assignment[] = [
  {
    id: "assign-1",
    courseId: "TEST-001",
    title: "Test Assignment 1",
    description: "Group Assignment\n\nComplete the test assignment instructions.",
    dueDate: "4/7/26, 11:59 PM CST",
    dueDateISO: "2026-04-07T23:59:00",
    maxPoints: 100,
    attempts: "Unlimited",
    type: "group",
    groupMembers: ["Test Member 1", "Test Member 2", "Test Member 3"],
  },
  {
    id: "assign-2",
    courseId: "TEST-001",
    title: "Test Assignment 2",
    description: "Individual Assignment\n\nComplete the short test task.",
    dueDate: "4/8/26, 11:59 PM CST",
    dueDateISO: "2026-04-08T23:59:00",
    maxPoints: 50,
    attempts: "1",
    type: "individual",
  },
  {
    id: "assign-3",
    courseId: "TEST-001",
    title: "Test Assignment 3",
    description: "Individual Assignment\n\nSubmit your response for test assignment 3.",
    dueDate: "4/10/26, 11:59 PM CST",
    dueDateISO: "2026-04-10T23:59:00",
    maxPoints: 50,
    attempts: "1",
    type: "individual",
  },
]